#
# MicroBlaze IO bus testbenches
#
# Copyright (c) 2022 Matt Liss
# BSD-3-Clause
#
Import('env')
env = env.Clone()

script_dir = Dir('.').srcnode().abspath
env.Append(VINCLUDES = [
        '-I'+script_dir+'/../memory/sdram',
        '-I'+script_dir+'/../opencores/i2c/rtl/verilog',
])

env.IVerilogTestBench('iobus_address_compare_tb',
        [ 'bench/iobus_address_compare_tb.v', 'iobus_address_compare.v'])

env.IVerilogTestBench('iobus_default_response_tb',
        [ 'bench/iobus_default_response_tb.v', 'iobus_default_response.v'])

env.IVerilogTestBench('iobus_output_mux_tb',
        [ 'bench/iobus_output_mux_tb.v', 'iobus_output_mux.v'])

env.IVerilogTestBench('iobus_top_tb', [
        'bench/iobus_top_tb.v',
        'bench/iobus_master_model.v',
        'iobus_address_compare.v',
        'iobus_default_response.v',
        'iobus_output_mux.v',
        'iobus_top.v',
        '../memory/sdram/bench/mt48lc32m8a2.v',
        '../memory/sdram/sdram_iom.v',
        '../memory/sdram/sdram.v',
        '../peripherals/gcnt/gcnt_iom.v',
        '../peripherals/i2cm/i2cm_iom.v',
        '../opencores/i2c/rtl/verilog/i2c_master_bit_ctrl.v',
        '../opencores/i2c/rtl/verilog/i2c_master_byte_ctrl.v',
        '../opencores/i2c/rtl/verilog/i2c_master_top.v',
        '../peripherals/pdm/pdm_iom.v',
        '../peripherals/pdm/pdm.v',
        '../peripherals/prng/prng_iom.v',
        '../peripherals/prng/prng.v',
        '../util/async_handshake.v',
        '../util/counter.v',
        '$ISE_PATH/verilog/src/glbl.v',
        '$ISE_PATH/verilog/src/unisims/IODELAY2.v',
        '$ISE_PATH/verilog/src/unisims/ODDR2.v',
])
