#
# Global Counter IO Module
#
# Copyright (c) 2022 Matt Liss
# BSD-3-Clause
#
Import('env')
env = env.Clone()

env.IVerilogTestBench('gcnt_iom_tb', [
        'bench/gcnt_iom_tb.v',
        'gcnt_iom.v',
        '../../util/counter.v',
        '../../mbiobus/bench/iobus_master_model.v'
])
